In [1]:
import numpy as np

# 1. Create

In [2]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.0383259 , 0.30214262, 0.3163832 , 0.9248263 ],
        [0.84938017, 0.61577627, 0.15042376, 0.5574974 ],
        [0.06104333, 0.84693416, 0.04198882, 0.90679805]],

       [[0.14398377, 0.21139325, 0.32701177, 0.77874617],
        [0.58091625, 0.79644872, 0.26816703, 0.59385836],
        [0.32726255, 0.02846491, 0.06292088, 0.35181163]]])

In [4]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [5]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [6]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
arr = np.array([[1,2,3],[1,2,3]])

In [8]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

# 2. Read

In [9]:
shape = data.shape
size = data.size
types = data.dtype

In [10]:
shape

(2, 3, 4)

In [11]:
size

24

In [12]:
types

dtype('float64')

In [13]:
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [14]:
arr

array([[0.0383259 , 0.30214262, 0.3163832 , 0.9248263 ],
       [0.84938017, 0.61577627, 0.15042376, 0.5574974 ],
       [0.06104333, 0.84693416, 0.04198882, 0.90679805]])

In [15]:
slicer

array([[[0.0383259 , 0.30214262, 0.3163832 , 0.9248263 ],
        [0.84938017, 0.61577627, 0.15042376, 0.5574974 ],
        [0.06104333, 0.84693416, 0.04198882, 0.90679805]],

       [[0.14398377, 0.21139325, 0.32701177, 0.77874617],
        [0.58091625, 0.79644872, 0.26816703, 0.59385836],
        [0.32726255, 0.02846491, 0.06292088, 0.35181163]]])

In [16]:
reverse

array([[0.14398377, 0.21139325, 0.32701177, 0.77874617],
       [0.58091625, 0.79644872, 0.26816703, 0.59385836],
       [0.32726255, 0.02846491, 0.06292088, 0.35181163]])

In [17]:
singleval

0.03832590060884056

# Update

In [18]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [22]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [23]:
list1

array([0.0114981 , 0.45650798, 0.37072875, 0.58314135, 0.3006783 ,
       0.77725503, 0.97598042, 0.32691154, 0.67820095, 0.58819268])

In [24]:
list2

array([0.09876449, 0.93602053, 0.41135471, 0.66940653, 0.92370834,
       0.81353092, 0.04102433, 0.98392548, 0.71738761, 0.4347301 ])

In [20]:
add

array([0.11026259, 1.39252851, 0.78208346, 1.25254787, 1.22438664,
       1.59078595, 1.01700475, 1.31083701, 1.39558856, 1.02292278])

In [21]:
sub

array([-0.08726639, -0.47951255, -0.04062595, -0.08626518, -0.62303004,
       -0.03627589,  0.9349561 , -0.65701394, -0.03918666,  0.15346258])

In [25]:
div

array([ 0.11641939,  0.4877115 ,  0.90123863,  0.87113185,  0.32551217,
        0.95540933, 23.7902851 ,  0.33225233,  0.94537589,  1.35300656])

In [26]:
mult

array([0.0011356 , 0.42730084, 0.15250102, 0.39035862, 0.27773905,
       0.632321  , 0.04003894, 0.32165659, 0.48653296, 0.25570506])

In [ ]:
#multiplys every number together and adds them together

In [27]:
dot

2.985289687112478

In [28]:
#for statistical function, remeber SAPLEMM

In [31]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = ([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [33]:
#exp is the logrithmic number of e

In [34]:
data[0][0][0] = 700

In [35]:
data

array([[[7.00000000e+02, 3.02142621e-01, 3.16383196e-01, 9.24826296e-01],
        [8.49380173e-01, 6.15776267e-01, 1.50423761e-01, 5.57497403e-01],
        [6.10433259e-02, 8.46934156e-01, 4.19888195e-02, 9.06798053e-01]],

       [[1.43983770e-01, 2.11393245e-01, 3.27011774e-01, 7.78746171e-01],
        [5.80916251e-01, 7.96448724e-01, 2.68167025e-01, 5.93858360e-01],
        [3.27262548e-01, 2.84649066e-02, 6.29208758e-02, 3.51811631e-01]]])

In [36]:
data.sort()
data

array([[[3.02142621e-01, 3.16383196e-01, 9.24826296e-01, 7.00000000e+02],
        [1.50423761e-01, 5.57497403e-01, 6.15776267e-01, 8.49380173e-01],
        [4.19888195e-02, 6.10433259e-02, 8.46934156e-01, 9.06798053e-01]],

       [[1.43983770e-01, 2.11393245e-01, 3.27011774e-01, 7.78746171e-01],
        [2.68167025e-01, 5.80916251e-01, 5.93858360e-01, 7.96448724e-01],
        [2.84649066e-02, 6.29208758e-02, 3.27262548e-01, 3.51811631e-01]]])

In [37]:
print(data.shape)

(2, 3, 4)


In [39]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [40]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [41]:
zeroes = np.insert(zeroes, 2,[2,3,4])
print(zeroes)

[0. 0. 2. 3. 4. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [42]:
data

array([[[3.02142621e-01, 3.16383196e-01, 9.24826296e-01, 7.00000000e+02,
         1.50423761e-01, 5.57497403e-01],
        [6.15776267e-01, 8.49380173e-01, 4.19888195e-02, 6.10433259e-02,
         8.46934156e-01, 9.06798053e-01]],

       [[1.43983770e-01, 2.11393245e-01, 3.27011774e-01, 7.78746171e-01,
         2.68167025e-01, 5.80916251e-01],
        [5.93858360e-01, 7.96448724e-01, 2.84649066e-02, 6.29208758e-02,
         3.27262548e-01, 3.51811631e-01]]])

In [43]:
np.delete(data, 0, axis=1)

array([[[0.61577627, 0.84938017, 0.04198882, 0.06104333, 0.84693416,
         0.90679805]],

       [[0.59385836, 0.79644872, 0.02846491, 0.06292088, 0.32726255,
         0.35181163]]])

In [45]:
data

array([[[3.02142621e-01, 3.16383196e-01, 9.24826296e-01, 7.00000000e+02,
         1.50423761e-01, 5.57497403e-01],
        [6.15776267e-01, 8.49380173e-01, 4.19888195e-02, 6.10433259e-02,
         8.46934156e-01, 9.06798053e-01]],

       [[1.43983770e-01, 2.11393245e-01, 3.27011774e-01, 7.78746171e-01,
         2.68167025e-01, 5.80916251e-01],
        [5.93858360e-01, 7.96448724e-01, 2.84649066e-02, 6.29208758e-02,
         3.27262548e-01, 3.51811631e-01]]])

In [46]:
np.save("new_array", data)